name: release-build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build (macos-${{ matrix.goarch }})
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          # Apple Silicon
          - goarch: arm64
            runner: macos-14
          # # Intel macOS
          # - goarch: amd64
          #   runner: macos-14-intel

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build
        run: |
          scripts/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ktt_macos_${{ matrix.goarch }}.release
          path: 'dist/*'
          retention-days: 1

  build-linux-amd64:
    name: Build (${{ matrix.name }} amd64)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: debian13
            image: 'debian:13'

          - name: debian12
            image: 'debian:12'

          # - name: ubuntu24
          #   image: 'ubuntu:24.04'

          # - name: ubuntu22
          #   image: 'ubuntu:22.04'

          # - name: rhel10
          #   image: 'redhat/ubi10:latest'

          # - name: rhel9
          #   image: 'redhat/ubi9:latest'

          # - name: rhel8
          #   image: 'redhat/ubi8:latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binaries via Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/package/Dockerfile.buildapp 
          platforms: linux/amd64
          outputs: type=local,dest=./dist
          provenance: false
          build-args: |
            BASE_IMAGE=${{matrix.image}}
            APP_VERSION=${{github.ref_name}}     

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ktt_linux_${{ matrix.name }}_amd64.release
          path: 'dist/*'
          retention-days: 1

  # build-linux-arm64:
  #   name: Build (${{ matrix.name }} arm64)
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       include:
  #         - name: debian13
  #           image: 'debian:13'

  #         - name: debian12
  #           image: 'debian:12'

  #         - name: ubuntu24
  #           image: 'ubuntu:24.04'

  #         - name: ubuntu22
  #           image: 'ubuntu:22.04'

  #         - name: rhel10
  #           image: 'redhat/ubi10:latest'

  #         - name: rhel9
  #           image: 'redhat/ubi9:latest'

  #         - name: rhel8
  #           image: 'redhat/ubi8:latest'

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build binaries via Docker
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: ./build/package/Dockerfile.buildapp 
  #         platforms: linux/arm64
  #         outputs: type=local,dest=./dist
  #         provenance: false

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: ktt_linux_${{ matrix.name }}_arm64.release
  #         path: 'dist/*'
  #         retention-days: 1


  release:
    needs:
      - build-macos
      - build-linux-amd64
      # - build-linux-arm64
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: '*.release'
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
